// <auto-generated />
namespace Doctor_Appointment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class drop_speciality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_speciality));
        
        string IMigrationMetadata.Id
        {
            get { return "202012091531117_drop_speciality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
