// <auto-generated />
namespace Doctor_Appointment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class off_isPatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(off_isPatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202012090830327_off_isPatient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
